### ISSUE TITLE
Error: GetId operation: Invalid login token. Incorrect token audience.

### ISSUE THREAD

**Issue by pgasiorowski** [catnekaise/cognito-idpool-auth#7]
Following this blog post I set up Cognito Identity Pool and role for Basic AuthFlow:
https://awsteele.com/blog/2023/10/25/aws-role-session-tags-for-github-actions.html

I also tried another workflow from catnekaise/cognito-idpool-basic-auth@alpha

The error I see is:

> An error occurred (NotAuthorizedException) when calling the GetId operation: Invalid login token. Incorrect token audience.

Any idea what may be wrong. How can I troubleshoot it?

**Comment by djonser** [comment]
@pgasiorowski this action and the other has `audience` as an input parameter with default value `cognito-identity.amazonaws.com`.

If using this default audience the GitHub Actions identity provider in AWS IAM must be configured with this value as one of its audiences.

The screenshot below shows the GitHub Actions identity provider configured to enable using his action with its default audience value.

<img width="1313" alt="image" src="https://github.com/catnekaise/cognito-idpool-auth/assets/8218022/c83ba21e-7356-492a-9fc3-0e2e7d06b51c">

**Comment by pgasiorowski** [comment]
I will give it a try. Thank you sir!

**Comment by pgasiorowski** [comment]
Confirmed. That was the missing piece!

Thanks for sharing this 👍
